@echo off
echo ============================================
echo   ZhongKao Mentor - PNG Asset Generator
echo ============================================
echo.
echo Generating all 4 PNG asset files...
echo.

echo [1/4] Generating icon.png (1024x1024)...
powershell -ExecutionPolicy Bypass -Command "Add-Type -AssemblyName System.Drawing; $b=New-Object System.Drawing.Bitmap(1024,1024); $g=[System.Drawing.Graphics]::FromImage($b); $g.SmoothingMode='AntiAlias'; $g.TextRenderingHint='AntiAlias'; $br=New-Object System.Drawing.Drawing2D.LinearGradientBrush([System.Drawing.Point]::new(0,0),[System.Drawing.Point]::new(1024,1024),[System.Drawing.Color]::FromArgb(255,102,187,106),[System.Drawing.Color]::FromArgb(255,56,142,60)); $g.FillRectangle($br,0,0,1024,1024); $br.Dispose(); $wb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White); $gb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,76,175,80)); $g.FillRectangle($wb,280,260,464,310); $g.FillRectangle($gb,280,260,35,310); for($i=1;$i -le 4;$i++){$ly=260+[int](310*(0.2+$i*0.15)); $g.FillRectangle((New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(80,165,214,167))),330,$ly,380,3)}; $gold=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,255,215,0)); $pts=@(); $rot=-1.5708; $step=0.6283; for($j=0;$j -lt 10;$j++){$r=if($j%%2 -eq 0){122}else{55}; $pts+=New-Object System.Drawing.PointF([float](740+[Math]::Cos($rot)*$r),[float](184+[Math]::Sin($rot)*$r)); $rot+=$step}; $g.FillPolygon($gold,$pts); $pts2=@(); $rot=-1.5708; for($j=0;$j -lt 10;$j++){$r=if($j%%2 -eq 0){72}else{32}; $pts2+=New-Object System.Drawing.PointF([float](256+[Math]::Cos($rot)*$r),[float](154+[Math]::Sin($rot)*$r)); $rot+=$step}; $g.FillPolygon($gold,$pts2); try{$tf=New-Object System.Drawing.Font('Microsoft YaHei',96,[System.Drawing.FontStyle]::Bold)}catch{try{$tf=New-Object System.Drawing.Font('SimHei',96,1)}catch{$tf=New-Object System.Drawing.Font('Arial',96,1)}}; $sf=New-Object System.Drawing.StringFormat; $sf.Alignment='Center'; $sf.LineAlignment='Center'; $g.DrawString([string][char]0x79C1+[string][char]0x4EBA+[string][char]0x5BFC+[string][char]0x5E08,$tf,$wb,512,780,$sf); try{$sf2=New-Object System.Drawing.Font('Microsoft YaHei',48)}catch{$sf2=New-Object System.Drawing.Font('Arial',48)}; $g.DrawString([string][char]0x79D1+[string][char]0x5B66+[string][char]0x80B2+[string][char]0x5A03+' '+[string][char]0x7CBE+[string][char]0x51C6+[string][char]0x63D0+[string][char]0x5206,$sf2,(New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(220,255,255,255))),512,900,$sf); $g.Dispose(); $b.Save('%~dp0icon.png',[System.Drawing.Imaging.ImageFormat]::Png); $b.Dispose(); Write-Host '  icon.png done' -ForegroundColor Green"

echo [2/4] Generating splash.png (1284x2778)...
powershell -ExecutionPolicy Bypass -Command "Add-Type -AssemblyName System.Drawing; $b=New-Object System.Drawing.Bitmap(1284,2778); $g=[System.Drawing.Graphics]::FromImage($b); $g.SmoothingMode='AntiAlias'; $g.TextRenderingHint='AntiAlias'; $br=New-Object System.Drawing.Drawing2D.LinearGradientBrush([System.Drawing.Point]::new(0,0),[System.Drawing.Point]::new(0,2778),[System.Drawing.Color]::FromArgb(255,102,187,106),[System.Drawing.Color]::FromArgb(255,56,142,60)); $g.FillRectangle($br,0,0,1284,2778); $br.Dispose(); $cb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(15,255,255,255)); $g.FillEllipse($cb,-200,-200,800,800); $g.FillEllipse($cb,700,1200,600,600); $wb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White); $gb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,76,175,80)); $g.FillRectangle($wb,322,920,640,220); $g.FillRectangle($gb,322,920,40,220); $gold=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,255,215,0)); $pts=@(); $rot=-1.5708; for($j=0;$j -lt 10;$j++){$r=if($j%%2 -eq 0){103}else{45}; $pts+=New-Object System.Drawing.PointF([float](835+[Math]::Cos($rot)*$r),[float](780+[Math]::Sin($rot)*$r)); $rot+=0.6283}; $g.FillPolygon($gold,$pts); try{$tf=New-Object System.Drawing.Font('Microsoft YaHei',128,[System.Drawing.FontStyle]::Bold)}catch{$tf=New-Object System.Drawing.Font('SimHei',128,1)}; $sf=New-Object System.Drawing.StringFormat; $sf.Alignment='Center'; $sf.LineAlignment='Center'; $g.DrawString([string][char]0x79C1+[string][char]0x4EBA+[string][char]0x5BFC+[string][char]0x5E08,$tf,$wb,642,1450,$sf); try{$sf2=New-Object System.Drawing.Font('Microsoft YaHei',56)}catch{$sf2=New-Object System.Drawing.Font('Arial',56)}; $g.DrawString([string][char]0x79D1+[string][char]0x5B66+[string][char]0x80B2+[string][char]0x5A03+[string][char]0xFF0C+[string][char]0x7CBE+[string][char]0x51C6+[string][char]0x63D0+[string][char]0x5206,$sf2,(New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(230,255,255,255))),642,1600,$sf); $lp=New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(80,255,255,255),2); $g.DrawLine($lp,257,2448,1027,2448); try{$vf=New-Object System.Drawing.Font('Microsoft YaHei',32)}catch{$vf=New-Object System.Drawing.Font('Arial',32)}; $g.DrawString('v1.0.0',$vf,(New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(128,255,255,255))),642,2560,$sf); $g.Dispose(); $b.Save('%~dp0splash.png',[System.Drawing.Imaging.ImageFormat]::Png); $b.Dispose(); Write-Host '  splash.png done' -ForegroundColor Green"

echo [3/4] Generating adaptive-icon.png (1024x1024)...
powershell -ExecutionPolicy Bypass -Command "Add-Type -AssemblyName System.Drawing; $b=New-Object System.Drawing.Bitmap(1024,1024); $g=[System.Drawing.Graphics]::FromImage($b); $g.SmoothingMode='AntiAlias'; $g.TextRenderingHint='AntiAlias'; $br=New-Object System.Drawing.Drawing2D.LinearGradientBrush([System.Drawing.Point]::new(0,0),[System.Drawing.Point]::new(1024,1024),[System.Drawing.Color]::FromArgb(255,102,187,106),[System.Drawing.Color]::FromArgb(255,56,142,60)); $g.FillRectangle($br,0,0,1024,1024); $br.Dispose(); $wb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White); $gb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,76,175,80)); $g.FillRectangle($wb,280,260,464,310); $g.FillRectangle($gb,280,260,35,310); for($i=1;$i -le 4;$i++){$ly=260+[int](310*(0.2+$i*0.15)); $g.FillRectangle((New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(80,165,214,167))),330,$ly,380,3)}; $gold=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,255,215,0)); $pts=@(); $rot=-1.5708; for($j=0;$j -lt 10;$j++){$r=if($j%%2 -eq 0){122}else{55}; $pts+=New-Object System.Drawing.PointF([float](740+[Math]::Cos($rot)*$r),[float](184+[Math]::Sin($rot)*$r)); $rot+=0.6283}; $g.FillPolygon($gold,$pts); $pts2=@(); $rot=-1.5708; for($j=0;$j -lt 10;$j++){$r=if($j%%2 -eq 0){72}else{32}; $pts2+=New-Object System.Drawing.PointF([float](256+[Math]::Cos($rot)*$r),[float](154+[Math]::Sin($rot)*$r)); $rot+=0.6283}; $g.FillPolygon($gold,$pts2); try{$tf=New-Object System.Drawing.Font('Microsoft YaHei',96,1)}catch{$tf=New-Object System.Drawing.Font('Arial',96,1)}; $sf=New-Object System.Drawing.StringFormat; $sf.Alignment='Center'; $sf.LineAlignment='Center'; $g.DrawString([string][char]0x79C1+[string][char]0x4EBA+[string][char]0x5BFC+[string][char]0x5E08,$tf,$wb,512,780,$sf); $g.Dispose(); $b.Save('%~dp0adaptive-icon.png',[System.Drawing.Imaging.ImageFormat]::Png); $b.Dispose(); Write-Host '  adaptive-icon.png done' -ForegroundColor Green"

echo [4/4] Generating favicon.png (48x48)...
powershell -ExecutionPolicy Bypass -Command "Add-Type -AssemblyName System.Drawing; $b=New-Object System.Drawing.Bitmap(48,48); $g=[System.Drawing.Graphics]::FromImage($b); $g.SmoothingMode='AntiAlias'; $gb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,76,175,80)); $wb=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White); $g.FillRectangle($gb,0,0,48,48); $g.FillRectangle($wb,14,16,22,16); $g.FillRectangle($gb,14,16,3,16); $gold=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255,255,215,0)); $pts=@(); $rot=-1.5708; for($j=0;$j -lt 10;$j++){$r=if($j%%2 -eq 0){7}else{3}; $pts+=New-Object System.Drawing.PointF([float](36+[Math]::Cos($rot)*$r),[float](12+[Math]::Sin($rot)*$r)); $rot+=0.6283}; $g.FillPolygon($gold,$pts); $g.Dispose(); $b.Save('%~dp0favicon.png',[System.Drawing.Imaging.ImageFormat]::Png); $b.Dispose(); Write-Host '  favicon.png done' -ForegroundColor Green"

echo.
echo ============================================
echo   All 4 PNG files generated!
echo ============================================
echo.
dir /b "%~dp0*.png"
echo.
pause
